### ISSUE TITLE
这样设置会6个DNS都同时查询吗？

### ISSUE THREAD

**Issue by PHCSJC** [import-yuefeng/smartDNS#4]
如果按下面这样设置，在DNS查询时，会对这6个DNS都进行并发查询吗？谢谢！

server-tcp 8.8.8.8
server-tcp 1.1.1.1

server-tls 8.8.8.8
server-tls 1.1.1.1

server-https https://1.1.1.1/dns-query
server-https https://8.8.8.8/resolve

**Comment by import-yuefeng** [comment]
可以贴一下你的完整配置文件吗？以供我具体看看

**Comment by jx-xysm** [comment]
@PHCSJC 你应该是搞错了项目，你这个格式的设置应该是这个smartdns
https://github.com/pymumu/smartdns

**Comment by PHCSJC** [comment]
是的，搞错了，抱歉
